import { useSyncExternalStore } from "react";

export type Language = "en" | "zh-CN";

const LANGUAGE_STORAGE_KEY = "app-language";
const DEFAULT_LANGUAGE: Language = "en";

export const i18n = {
  en: {
    loginDescription: "A qbittorrent client via Tauri",
    domainPlaceholder: "Enter domain (with http/https) ...",
    usernamePlaceholder: "Enter a username...",
    passwordPlaceholder: "Enter a password...",
    login: "Login",
    autoLoginFailed: "Auto-login failed",
    loginFailed: "Login failed",
    devAutoLogin: "Dev mode: auto-logging in as",
    toolbarAdd: "Add",
    toolbarPause: "Pause",
    toolbarResume: "Resume",
    toolbarDelete: "Delete",
    torrentCount: (count: number) => `${count} torrents`,
    selectedCount: (count: number) => `${count} selected`,
    dropTorrentFile: "Drop .torrent file to add",
    filters: {
      all: "All",
      downloading: "Downloading",
      completed: "Completed",
      paused: "Paused",
      active: "Active",
      inactive: "Inactive",
      stalled: "Stalled",
      errored: "Errored",
    },
    categories: "Categories",
    expandCategories: "Expand categories",
    collapseCategories: "Collapse categories",
    allCategories: "All categories",
    uncategorized: "Uncategorized",
    openSettings: "Open settings",
    expandSidebar: "Expand sidebar",
    collapseSidebar: "Collapse sidebar",
    settings: "Settings",
    total: "total",
    nodes: "nodes",
    tableName: "Name",
    tableSize: "Size",
    tableProgress: "Progress",
    tableStatus: "Status",
    tableSpeed: "Speed",
    tableSeeds: "Seeds",
    tablePeers: "Peers",
    tableEta: "ETA",
    tableRatio: "Ratio",
    noTorrentsFound: "No torrents found",
    stateDownloading: "Downloading",
    stateSeeding: "Seeding",
    statePaused: "Paused",
    stateCompleted: "Completed",
    stateStalledDown: "Stalled ↓",
    stateStalledUp: "Stalled ↑",
    stateChecking: "Checking",
    stateQueued: "Queued",
    stateError: "Error",
    stateMissingFiles: "Missing Files",
    stateMoving: "Moving",
    stateAllocating: "Allocating",
    stateUnknown: "Unknown",
    done: "Done",
    addTorrent: "Add Torrent",
    urlMagnet: "URL / Magnet",
    torrentFile: "Torrent File",
    urlsMagnetLinks: "URLs / Magnet Links",
    oneUrlPerLine: "One URL or magnet link per line",
    clickSelectTorrent: "Click to select a",
    torrentFileSuffix: "file",
    savePath: "Save Path",
    default: "Default",
    category: "Category",
    none: "None",
    addPaused: "Add in paused state",
    cancel: "Cancel",
    adding: "Adding...",
    enterUrlError: "Please enter at least one URL or magnet link.",
    selectFileError: "Please select a .torrent file.",
    deleteTorrentTitle: (count: number) => `Delete Torrent${count > 1 ? "s" : ""}`,
    removeTorrentQuestion: (count: number) => `Remove ${count} torrent${count > 1 ? "s" : ""}?`,
    alsoDeleteFiles: "Also delete downloaded files",
    commandPalette: "Command palette",
    commandPaletteDescription: "Search torrents, categories, and settings, then press Enter to navigate.",
    commandPalettePlaceholder: "Search torrents, categories, and settings...",
    enterToOpen: "Enter to open",
    noMatchingCommands: "No matching commands",
    unlimited: "Unlimited",
    custom: "Custom...",
    torrentFallback: "Torrent",
    downloadLimit: "Download Limit",
    uploadLimit: "Upload Limit",
    forceRecheck: "Force Recheck",
    forceReannounce: "Force Reannounce",
    downloadTorrent: "Download .torrent",
    downloadingTorrentFile: "Downloading torrent file",
    downloadTorrentFailed: "Failed to download torrent file",
    limitWarning: (type: string, limit: string, global: string) =>
      `${type} limit (${limit}) exceeds the global limit (${global}). The global limit will take precedence.`,
    download: "Download",
    upload: "Upload",
    speedLimit: "Speed Limit",
    apply: "Apply",
    speedPlaceholder: "e.g. 512",
    close: "Close",
    closeQbitview: "Close qBitView",
    closeQbitviewDescription: "Choose what to do with the application.",
    rememberCloseChoice: "Remember this choice",
    minimizeToTray: "Minimize to tray",
    quitApplication: "Quit application",
    drawerTabs: {
      info: "Info",
      trackers: "Trackers",
      peers: "Peers",
      webseeds: "HTTP Sources",
      content: "Content",
    },
    noData: "No data",
    savePathInfo: "Save Path",
    comment: "Comment",
    totalSize: "Total Size",
    pieceSize: "Piece Size",
    pieces: "Pieces",
    shareRatio: "Share Ratio",
    connections: "Connections",
    downloaded: "Downloaded",
    uploaded: "Uploaded",
    avgDown: "Avg ↓",
    avgUp: "Avg ↑",
    activeTime: "Active Time",
    seedingTimeInfo: "Seeding Time",
    createdBy: "Created By",
    added: "Added",
    piecesDownloaded: "Downloaded",
    piecesDownloading: "Downloading",
    piecesMissing: "Missing",
    pieceDownloadingCount: (count: number) => `${count} piece${count > 1 ? "s" : ""} downloading`,
    noTrackers: "No trackers",
    status: "Status",
    tier: "Tier",
    noConnectedPeers: "No connected peers",
    client: "Client",
    noHttpSources: "No HTTP sources",
    noFiles: "No files",
    collapseFolder: "Collapse folder",
    expandFolder: "Expand folder",
    copiedNameHash: "Copied name and hash",
    copyNameHash: "Copy name and hash",
    loading: "Loading...",
    commandCategoryTitle: (label: string) => `Category: ${label}`,
    commandSwitchFilter: (label: string) => `Switch to the ${label.toLowerCase()} list`,
    unnamedTorrent: "Unnamed torrent",
    settingsCommands: {
      theme: ["Settings: Theme", "Choose light, dark, or follow system"],
      closeAction: ["Settings: Close behavior", "Choose what happens when the window is closed"],
      savePath: ["Settings: Save path", "Jump to the default download location"],
      tempPath: ["Settings: Temporary path", "Jump to incomplete download storage"],
      listenPort: ["Settings: Listen port", "Jump to the incoming connection port"],
      downloadLimit: ["Settings: Download limit", "Jump to the global download rate limit"],
      uploadLimit: ["Settings: Upload limit", "Jump to the global upload rate limit"],
      maxActiveDownloads: ["Settings: Max active downloads", "Jump to queue limits"],
      maxConnections: ["Settings: Max connections", "Jump to connection limits"],
      encryption: ["Settings: Encryption mode", "Jump to BitTorrent protocol privacy"],
      maxRatio: ["Settings: Maximum ratio", "Jump to seeding stop conditions"],
      maxSeedingTime: ["Settings: Seeding time", "Jump to the seeding time limit"],
    },
    updateAvailable: "Update Available",
    updateAvailableDescription: (version: string) => `qBitView ${version} is available.`,
    updateNotes: "Release Notes",
    installUpdate: "Install Update",
    remindLater: "Later",
    downloadProgress: (percent: number) => `Downloading... ${percent}%`,
    readyToRestart: "Update installed. Restart to apply.",
    restartNow: "Restart Now",
  },
  "zh-CN": {
    loginDescription: "基于 Tauri 的 qBittorrent 客户端",
    domainPlaceholder: "输入地址（包含 http/https）...",
    usernamePlaceholder: "输入用户名...",
    passwordPlaceholder: "输入密码...",
    login: "登录",
    autoLoginFailed: "自动登录失败",
    loginFailed: "登录失败",
    devAutoLogin: "开发模式：自动登录为",
    toolbarAdd: "添加",
    toolbarPause: "暂停",
    toolbarResume: "继续",
    toolbarDelete: "删除",
    torrentCount: (count: number) => `${count} 个种子`,
    selectedCount: (count: number) => `已选择 ${count} 个`,
    dropTorrentFile: "拖放 .torrent 文件以添加",
    filters: {
      all: "全部",
      downloading: "下载中",
      completed: "已完成",
      paused: "已暂停",
      active: "活动",
      inactive: "非活动",
      stalled: "停滞",
      errored: "错误",
    },
    categories: "分类",
    expandCategories: "展开分类",
    collapseCategories: "折叠分类",
    allCategories: "全部分类",
    uncategorized: "未分类",
    openSettings: "打开设置",
    expandSidebar: "展开侧边栏",
    collapseSidebar: "折叠侧边栏",
    settings: "设置",
    total: "总计",
    nodes: "节点",
    tableName: "名称",
    tableSize: "大小",
    tableProgress: "进度",
    tableStatus: "状态",
    tableSpeed: "速度",
    tableSeeds: "种子",
    tablePeers: "用户",
    tableEta: "剩余时间",
    tableRatio: "分享率",
    noTorrentsFound: "未找到种子",
    stateDownloading: "下载中",
    stateSeeding: "做种中",
    statePaused: "已暂停",
    stateCompleted: "已完成",
    stateStalledDown: "下载停滞",
    stateStalledUp: "上传停滞",
    stateChecking: "校验中",
    stateQueued: "排队中",
    stateError: "错误",
    stateMissingFiles: "文件缺失",
    stateMoving: "移动中",
    stateAllocating: "分配中",
    stateUnknown: "未知",
    done: "完成",
    addTorrent: "添加种子",
    urlMagnet: "URL / 磁力链接",
    torrentFile: "种子文件",
    urlsMagnetLinks: "URL / 磁力链接",
    oneUrlPerLine: "每行一个 URL 或磁力链接",
    clickSelectTorrent: "点击选择",
    torrentFileSuffix: "文件",
    savePath: "保存路径",
    default: "默认",
    category: "分类",
    none: "无",
    addPaused: "添加后保持暂停",
    cancel: "取消",
    adding: "添加中...",
    enterUrlError: "请输入至少一个 URL 或磁力链接。",
    selectFileError: "请选择一个 .torrent 文件。",
    deleteTorrentTitle: () => "删除种子",
    removeTorrentQuestion: (count: number) => `删除 ${count} 个种子？`,
    alsoDeleteFiles: "同时删除已下载文件",
    commandPalette: "命令面板",
    commandPaletteDescription: "搜索种子、分类和设置，然后按 Enter 跳转。",
    commandPalettePlaceholder: "搜索种子、分类和设置...",
    enterToOpen: "Enter 打开",
    noMatchingCommands: "没有匹配的命令",
    unlimited: "不限速",
    custom: "自定义...",
    torrentFallback: "种子",
    downloadLimit: "下载限制",
    uploadLimit: "上传限制",
    forceRecheck: "强制校验",
    forceReannounce: "强制汇报",
    downloadTorrent: "下载 .torrent",
    downloadingTorrentFile: "正在下载种子文件",
    downloadTorrentFailed: "下载种子文件失败",
    limitWarning: (type: string, limit: string, global: string) =>
      `${type}限制（${limit}）超过全局限制（${global}），将优先使用全局限制。`,
    download: "下载",
    upload: "上传",
    speedLimit: "速度限制",
    apply: "应用",
    speedPlaceholder: "例如 512",
    close: "关闭",
    closeQbitview: "关闭 qBitView",
    closeQbitviewDescription: "选择如何处理应用。",
    rememberCloseChoice: "记住这个选择",
    minimizeToTray: "最小化到托盘",
    quitApplication: "退出应用",
    drawerTabs: {
      info: "信息",
      trackers: "Tracker",
      peers: "用户",
      webseeds: "HTTP 来源",
      content: "内容",
    },
    noData: "无数据",
    savePathInfo: "保存路径",
    comment: "注释",
    totalSize: "总大小",
    pieceSize: "分片大小",
    pieces: "分片",
    shareRatio: "分享率",
    connections: "连接",
    downloaded: "已下载",
    uploaded: "已上传",
    avgDown: "平均下载",
    avgUp: "平均上传",
    activeTime: "活动时间",
    seedingTimeInfo: "做种时间",
    createdBy: "创建者",
    added: "添加时间",
    piecesDownloaded: "已下载",
    piecesDownloading: "下载中",
    piecesMissing: "缺失",
    pieceDownloadingCount: (count: number) => `${count} 个分片正在下载`,
    noTrackers: "无 Tracker",
    status: "状态",
    tier: "层级",
    noConnectedPeers: "无已连接用户",
    client: "客户端",
    noHttpSources: "无 HTTP 来源",
    noFiles: "无文件",
    collapseFolder: "折叠文件夹",
    expandFolder: "展开文件夹",
    copiedNameHash: "已复制名称和哈希",
    copyNameHash: "复制名称和哈希",
    loading: "加载中...",
    commandCategoryTitle: (label: string) => `分类：${label}`,
    commandSwitchFilter: (label: string) => `切换到${label}列表`,
    unnamedTorrent: "未命名种子",
    settingsCommands: {
      theme: ["设置：主题", "选择浅色、深色或跟随系统"],
      closeAction: ["设置：关闭行为", "选择关闭窗口时执行的操作"],
      savePath: ["设置：保存路径", "跳转到默认下载位置"],
      tempPath: ["设置：临时路径", "跳转到未完成下载存储位置"],
      listenPort: ["设置：监听端口", "跳转到传入连接端口"],
      downloadLimit: ["设置：下载限制", "跳转到全局下载速度限制"],
      uploadLimit: ["设置：上传限制", "跳转到全局上传速度限制"],
      maxActiveDownloads: ["设置：最大活动下载数", "跳转到队列限制"],
      maxConnections: ["设置：最大连接数", "跳转到连接限制"],
      encryption: ["设置：加密模式", "跳转到 BitTorrent 协议隐私设置"],
      maxRatio: ["设置：最大分享率", "跳转到做种停止条件"],
      maxSeedingTime: ["设置：做种时间", "跳转到做种时间限制"],
    },
    updateAvailable: "发现新版本",
    updateAvailableDescription: (version: string) => `qBitView ${version} 已发布。`,
    updateNotes: "更新说明",
    installUpdate: "立即安装",
    remindLater: "稍后再说",
    downloadProgress: (percent: number) => `正在下载... ${percent}%`,
    readyToRestart: "更新已安装，重启后生效。",
    restartNow: "立即重启",
  },
} as const;

export type I18n = (typeof i18n)[Language];

export const settingsI18n = {
  en: {
    unsavedTitle: "Unsaved settings",
    unsavedDescription: "You have unsaved changes. Save before leaving settings?",
    discardAndLeave: "Leave without saving",
    saveAndLeave: "Save and leave",
    back: "Back",
    settings: "Settings",
    reset: "Reset",
    save: "Save",
    saved: "Saved",
    loadFailed: "Failed to load settings",
    saveFailed: "Save failed",
    appearance: "Appearance",
    appearanceDescription: "Choose app theme and language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "Follow system",
    language: "Language",
    english: "English",
    chinese: "中文",
    closeBehavior: "Close behavior",
    closeBehaviorDescription: "What happens when the window is closed",
    onClose: "On close",
    askEveryTime: "Ask every time",
    quitApplication: "Quit application",
    runInBackground: "Run in background",
    paths: "Paths",
    pathsDescription: "Download and temporary storage",
    savePath: "Save path",
    savePathPlaceholder: "e.g. /downloads",
    enableTemporaryPath: "Enable temporary path",
    temporaryPath: "Temporary path",
    tempPathPlaceholder: "e.g. /tmp",
    connectivity: "Connectivity",
    connectivityDescription: "Ports and connection behavior",
    listenPort: "Listen port",
    listenPortPlaceholder: "e.g. 6881",
    randomizePort: "Randomize port on start",
    enableUpnp: "Enable UPnP / NAT-PMP",
    speedQueue: "Speed and Queue",
    speedQueueDescription: "Global limits and active tasks",
    downloadLimit: "Download limit (KiB/s)",
    uploadLimit: "Upload limit (KiB/s)",
    unlimitedPlaceholder: "0 means unlimited",
    maxActiveDownloads: "Max active downloads",
    maxActiveDownloadsPlaceholder: "e.g. 3",
    maxActiveUploads: "Max active uploads",
    maxActiveUploadsPlaceholder: "e.g. 2",
    maxActiveTorrents: "Max active torrents",
    maxActiveTorrentsPlaceholder: "e.g. 4",
    startPaused: "Start torrents paused",
    connectionsSlots: "Connections and Slots",
    connectionsSlotsDescription: "Connection and upload slot limits",
    maxConnections: "Max connections",
    maxConnectionsPlaceholder: "e.g. 500",
    maxConnectionsPerTorrent: "Max connections per torrent",
    maxConnectionsPerTorrentPlaceholder: "e.g. 50",
    maxUploadSlots: "Max upload slots",
    maxUploadSlotsPlaceholder: "e.g. 20",
    maxUploadSlotsPerTorrent: "Max upload slots per torrent",
    maxUploadSlotsPerTorrentPlaceholder: "e.g. 10",
    bittorrent: "BitTorrent",
    bittorrentDescription: "Protocol and privacy",
    enableDht: "Enable DHT",
    enablePex: "Enable PeX",
    enableLsd: "Enable Local Discovery (LSD)",
    encryptionMode: "Encryption mode",
    prefer: "Prefer",
    force: "Force",
    disable: "Disable",
    seeding: "Seeding",
    seedingDescription: "Stop seeding after conditions are met",
    enableRatioLimit: "Enable ratio limit",
    maximumRatio: "Maximum ratio",
    maximumRatioPlaceholder: "e.g. 2.0",
    actionOnRatioHit: "Action on ratio hit",
    stop: "Stop",
    pause: "Pause",
    remove: "Remove",
    enableSeedingTimeLimit: "Enable seeding time limit",
    seedingTime: "Seeding time (minutes)",
    seedingTimePlaceholder: "e.g. 60",
    disk: "Disk",
    diskDescription: "Write behavior for downloaded files",
    preallocateAll: "Pre-allocate disk space for all files",
  },
  "zh-CN": {
    unsavedTitle: "有未保存的配置",
    unsavedDescription: "你有未保存的修改，是否保存后再退出设置？",
    discardAndLeave: "不保存退出",
    saveAndLeave: "保存并退出",
    back: "返回",
    settings: "设置",
    reset: "重置",
    save: "保存",
    saved: "已保存",
    loadFailed: "加载设置失败",
    saveFailed: "保存失败",
    appearance: "外观",
    appearanceDescription: "选择应用主题和语言",
    theme: "主题",
    light: "浅色",
    dark: "深色",
    system: "跟随系统",
    language: "语言",
    english: "English",
    chinese: "中文",
    closeBehavior: "关闭行为",
    closeBehaviorDescription: "关闭窗口时执行的操作",
    onClose: "关闭时",
    askEveryTime: "每次询问",
    quitApplication: "退出应用",
    runInBackground: "后台运行",
    paths: "路径",
    pathsDescription: "下载和临时存储位置",
    savePath: "保存路径",
    savePathPlaceholder: "例如 /downloads",
    enableTemporaryPath: "启用临时路径",
    temporaryPath: "临时路径",
    tempPathPlaceholder: "例如 /tmp",
    connectivity: "连接",
    connectivityDescription: "端口和连接行为",
    listenPort: "监听端口",
    listenPortPlaceholder: "例如 6881",
    randomizePort: "启动时随机端口",
    enableUpnp: "启用 UPnP / NAT-PMP",
    speedQueue: "速度和队列",
    speedQueueDescription: "全局限速和活动任务",
    downloadLimit: "下载限制 (KiB/s)",
    uploadLimit: "上传限制 (KiB/s)",
    unlimitedPlaceholder: "0 表示不限速",
    maxActiveDownloads: "最大活动下载数",
    maxActiveDownloadsPlaceholder: "例如 3",
    maxActiveUploads: "最大活动上传数",
    maxActiveUploadsPlaceholder: "例如 2",
    maxActiveTorrents: "最大活动种子数",
    maxActiveTorrentsPlaceholder: "例如 4",
    startPaused: "添加种子时暂停",
    connectionsSlots: "连接和槽位",
    connectionsSlotsDescription: "连接数和上传槽限制",
    maxConnections: "最大连接数",
    maxConnectionsPlaceholder: "例如 500",
    maxConnectionsPerTorrent: "单种子最大连接数",
    maxConnectionsPerTorrentPlaceholder: "例如 50",
    maxUploadSlots: "最大上传槽",
    maxUploadSlotsPlaceholder: "例如 20",
    maxUploadSlotsPerTorrent: "单种子最大上传槽",
    maxUploadSlotsPerTorrentPlaceholder: "例如 10",
    bittorrent: "BitTorrent",
    bittorrentDescription: "协议和隐私",
    enableDht: "启用 DHT",
    enablePex: "启用 PeX",
    enableLsd: "启用本地发现 (LSD)",
    encryptionMode: "加密模式",
    prefer: "优先",
    force: "强制",
    disable: "禁用",
    seeding: "做种",
    seedingDescription: "满足条件后停止做种",
    enableRatioLimit: "启用分享率限制",
    maximumRatio: "最大分享率",
    maximumRatioPlaceholder: "例如 2.0",
    actionOnRatioHit: "达到分享率后的操作",
    stop: "停止",
    pause: "暂停",
    remove: "删除",
    enableSeedingTimeLimit: "启用做种时间限制",
    seedingTime: "做种时间（分钟）",
    seedingTimePlaceholder: "例如 60",
    disk: "磁盘",
    diskDescription: "下载文件写入行为",
    preallocateAll: "为所有文件预分配磁盘空间",
  },
} satisfies Record<Language, Record<string, string>>;

const listeners = new Set<() => void>();
let currentLanguage = readStoredLanguage();
let hasPreviewLanguage = false;

function isLanguage(value: string | null): value is Language {
  return value === "en" || value === "zh-CN";
}

function readStoredLanguage(): Language {
  if (typeof window === "undefined") return DEFAULT_LANGUAGE;
  const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return isLanguage(stored) ? stored : DEFAULT_LANGUAGE;
}

function notifyLanguageChange() {
  listeners.forEach((listener) => listener());
}

function subscribe(listener: () => void) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

export function getLanguage(): Language {
  if (!hasPreviewLanguage) {
    currentLanguage = readStoredLanguage();
  }
  return currentLanguage;
}

export function applyLanguage(language: Language) {
  hasPreviewLanguage = true;
  currentLanguage = language;
  if (typeof document !== "undefined") {
    document.documentElement.lang = language === "zh-CN" ? "zh-CN" : "en";
  }
  notifyLanguageChange();
}

export function setLanguage(language: Language) {
  if (typeof window !== "undefined") {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  }
  applyLanguage(language);
  hasPreviewLanguage = false;
}

export function initLanguage() {
  hasPreviewLanguage = false;
  applyLanguage(readStoredLanguage());
  hasPreviewLanguage = false;
}

export function useLanguage() {
  return useSyncExternalStore(subscribe, getLanguage, () => DEFAULT_LANGUAGE);
}

export function useI18n(): I18n {
  return i18n[useLanguage()];
}
